### ISSUE TITLE
Update, fix and improve Influence Functions notebooks

### ISSUE THREAD

**Issue by AnesBenmerzoug** [aai-institute/pyDVL#430]
- [x] Apply tags to hide import cells.
- [x] Fix rendering of certain math equations in influence imagenet notebook.
- [ ]  ~~Consider using pytorch lightning instead of custom TrainingManager class. See #351~~
- [x] Remove extra empty cell in influence synthetic notebook.
- [x] Fix usage of `support` module
